alibaba/dragonwell8_hotspot

test/jwarmup/TestClassInitChain.java
Summary:
fix typo error in test case
Test Plan: test/jwarmup/TestClassInitChain.java
Reviewed-by: luchsh
Issue: https://github.com/alibaba/dragonwell8/issues/16
=> [JWarmUp] fix test error of TestClassInitChain.java

src/share/vm/jfr/dcmd/jfrDcmds.cpp, src/share/vm/jfr/dcmd/jfrDcmds.hpp, src/share/vm/runtime/globals.hpp, test/jfr/test_unlockCommercialFeatures_compatibility.sh
Summary: add compatibility for UnlockCommercialFeatures
Reviewed-by: yfxhust, luchsh
=> [JFR] Add compatibility for UnlockCommercialFeatures

src/share/vm/classfile/vmSymbols.hpp, src/share/vm/services/diagnosticCommand.cpp, src/share/vm/services/diagnosticCommand.hpp, test/jwarmup/jcmd/TestInvokeJWarmupViaJcmd.java
Summary: Invoke JWarmup APIs via jcmd
Test Plan: test/jwarmup/jcmd/TestInvokeJWarmupViaJcmd.java
Reviewers: kuaiwei, luchsh
Issue: https://aone.alibaba-inc.com/task/22023553
CR: https://aone.alibaba-inc.com/task/22023553
=> [JWarmup] Invoke JWarmup via jcmd

make/windows/makefiles/vm.make, src/share/vm/jwarmup/jitWarmUp.cpp
Summary:
change build script and to code to support windows platform
Test Plan:
existing test cases
Reviewers:
@shiyuexw @luchsh @sanhong 
Issue:
https://github.com/alibaba/dragonwell8/issues/51
CR:
https://github.com/alibaba/dragonwell8_hotspot/pull/15
=> [JWarmUp] change for windows build

make/bsd/makefiles/buildtree.make, make/bsd/makefiles/trace.make, make/bsd/makefiles/vm.make, make/windows/create_obj_files.sh, make/windows/makefiles/trace.make, src/cpu/x86/vm/rdtsc_x86.cpp, src/share/vm/opto/superword.hpp, src/share/vm/runtime/arguments.cpp, src/share/vm/utilities/macros.hpp, src/share/vm/utilities/ticks.hpp
Test Plan: existing test cases
Reviewed-by: shiyue, kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/52
=> Summary: Disable JFR support in windows/mac build

src/share/vm/classfile/classLoaderData.cpp
Test Plan: existing test cases
Reviewed-by: shiyue
Issue: https://github.com/alibaba/dragonwell8/issues/52
=> Summary: Fix debug build failure

make/bsd/makefiles/mapfile-vers-debug, make/bsd/makefiles/mapfile-vers-product
Summary: add jwarmup symbols to mapfile
Test Plan: build successful
Reviewers: shiyue, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/53
CR: https://github.com/alibaba/dragonwell8_hotspot/pull/18
=> [JWarmUp] add symbol for mac build

src/share/vm/gc_implementation/g1/elasticHeap.cpp, src/share/vm/jfr/periodic/jfrThreadCPULoadEvent.cpp, src/share/vm/jfr/utilities/jfrJavaLog.cpp
Summary: Fixed following build failure caused by -Werror=format-security
Test Plan: build and sanity test
Reviewed-by: D-D-H, mmyxym
Issue: https://github.com/alibaba/dragonwell8/issues/79
=> [Misc] Fixed compilation failure on gcc 7.4

.github/workflows/check_pr.yml
Summary: added workflow to check pull request
Test Plan: workflow shipped with this PR
Reviewed-by: kuaiwei, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/80
=> [Misc] Added workflow to check pull request

.github/workflows/check_pr.yml, src/share/vm/gc_interface/allocTracer.inline.hpp
Summary: fix some misc things to build fastdebug version dragonwell8
Test Plan: build Dragonwell in fastdebug mode
Reviewed-by: luchsh,sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/82
=> [Misc] Solve fastdebug build issues

src/share/vm/gc_implementation/g1/g1AllocRegion.cpp, src/share/vm/gc_implementation/g1/g1CollectedHeap.cpp, src/share/vm/gc_implementation/g1/g1TenantAllocationContext.cpp, src/share/vm/gc_implementation/g1/g1TenantAllocationContext.hpp, src/share/vm/prims/jvm.cpp, src/share/vm/prims/tenantenv.cpp, src/share/vm/runtime/arguments_ext.cpp, src/share/vm/runtime/globals_ext.hpp, src/share/vm/services/nmtCommon.cpp, test/multi-tenant/TestContainerOf.java, test/multi-tenant/TestTenantHeapLimit.java, test/multi-tenant/TestTenantJVMOptions.sh, test/multi-tenant/TestTenantMemoryMTSafe.java, test/multi-tenant/TestTenantNMTSupport.java
Summary: ported heap throttling feature of MultiTenant to Dragonwell8
Test Plan: hotspot/test/multi-tenant/
Reviewed-by: luchsh, mmyxym
Issue: https://github.com/alibaba/dragonwell8/issues/91
=> [MultiTenant] Support TenantHeapThrottling

src/share/vm/classfile/vmSymbols.hpp, src/share/vm/prims/tenantenv.cpp, src/share/vm/runtime/globals_ext.hpp, src/share/vm/runtime/thread.cpp
Summary: added two new options to support tenant cpu controlling
Test Plan: jdk/test/multi-tenant
Reviewed-by: yuleil, superajun-wsj
Issue: https://github.com/alibaba/dragonwell8/issues/84
=> [MultiTenant] Added -XX:+TenantCpuThrottling -XX:+TenantCpuAccounting

src/share/vm/prims/tenantenv.cpp, src/share/vm/runtime/globals_ext.hpp
Summary: added new flag -XX:+TenantDataIsolation
Test Plan: jdk/test/multi-tenant
Reviewed-by: yuleil, superajun-wsj
Issue: https://github.com/alibaba/dragonwell8/issues/84
=> [MultiTenant] Added new flag -XX:+TenantDataIsolation

src/share/vm/classfile/javaClasses.cpp, src/share/vm/gc_implementation/g1/g1AllocationContext.cpp, src/share/vm/prims/jvm.h, src/share/vm/prims/tenantenv.cpp, src/share/vm/runtime/arguments_ext.cpp, src/share/vm/runtime/thread.cpp, test/multi-tenant/TestContainerOf.java, test/multi-tenant/TestHeapIsolation.java, test/multi-tenant/TestParGCAllocatorLeak.sh, test/multi-tenant/TestPerTenantTLAB.java, test/multi-tenant/TestTenantHeapLimit.java, test/multi-tenant/TestTenantJVMOptions.sh, test/multi-tenant/TestTenantMemoryMTSafe.java, test/multi-tenant/TestTenantNMTSupport.java
Summary: Fixed build failure on Windows by disabling CPU related features
Test Plan: hotspot/test/sanity
Reviewed-by: kuaiwei, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/92
=> [MultiTenant] Fixed build failure on Windows

src/share/vm/gc_implementation/g1/g1CollectedHeap.cpp, src/share/vm/gc_implementation/g1/g1CollectedHeap.hpp, src/share/vm/gc_implementation/g1/vm_operations_g1.cpp, src/share/vm/gc_implementation/g1/vm_operations_g1.hpp, test/multi-tenant/TestTenantGCCause.java
Summary: Print Tenant ID in GC log of tenant triggered GC
Test Plan: hotspot/test/multi-tenant/
Reviewed-by: luchsh, mmyxym
Issue: https://github.com/alibaba/dragonwell8/issues/102
=> [MultiTenant] Print tenant ID in GC log of tenant triggerred GC

src/cpu/x86/vm/sharedRuntime_x86_32.cpp, src/cpu/x86/vm/sharedRuntime_x86_64.cpp, src/os/windows/vm/os_windows.cpp, src/os_cpu/bsd_x86/vm/threadLS_bsd_x86.cpp, src/os_cpu/linux_x86/vm/threadLS_linux_x86.cpp, src/os_cpu/windows_x86/vm/threadLS_windows_x86.cpp, src/share/vm/classfile/javaClasses.cpp, src/share/vm/classfile/javaClasses.hpp, src/share/vm/classfile/systemDictionary.hpp, src/share/vm/classfile/vmSymbols.hpp, src/share/vm/prims/jni.cpp, src/share/vm/prims/jvm.cpp, src/share/vm/prims/nativeLookup.cpp, src/share/vm/prims/unsafe.cpp, src/share/vm/runtime/coroutine.cpp, src/share/vm/runtime/coroutine.hpp, src/share/vm/runtime/frame.cpp, src/share/vm/runtime/frame.hpp, src/share/vm/runtime/globals_ext.hpp, src/share/vm/runtime/handles.cpp, src/share/vm/runtime/handles.hpp, src/share/vm/runtime/javaCalls.cpp, src/share/vm/runtime/javaCalls.hpp, src/share/vm/runtime/thread.cpp, src/share/vm/runtime/thread.hpp, src/share/vm/runtime/threadLocalStorage.cpp, src/share/vm/runtime/threadLocalStorage.hpp, src/share/vm/utilities/debug.cpp, src/share/vm/utilities/debug.hpp
Summary:
- From http://hg.openjdk.java.net/mlvm/mlvm/hotspot/file/4cd7d914b0e3/coro-simple.patch.
- Resolve trivial conflicts in: systemDictionary.hpp, thread.cpp, debug.hpp.
- Add an option "EnableCoroutine".
Test Plan: run jtreg tests
Reviewed-by: yuleil, shiyuexw, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/113
=> [Coroutine] Import coroutine patch

src/cpu/x86/vm/interp_masm_x86_64.cpp, src/cpu/x86/vm/sharedRuntime_x86_32.cpp, src/cpu/x86/vm/sharedRuntime_x86_64.cpp, src/share/vm/code/nmethod.cpp, src/share/vm/prims/jvmtiThreadState.cpp, src/share/vm/prims/unsafe.cpp, src/share/vm/runtime/coroutine.cpp, src/share/vm/runtime/coroutine.hpp, src/share/vm/runtime/handles.hpp, src/share/vm/runtime/thread.cpp, src/share/vm/runtime/thread.hpp, test/runtime/coroutine/Issue11230146.java, test/runtime/coroutine/SimpleWispTest.java, test/runtime/coroutine/TestAvoidDeoptCoroutineMethod.java, test/runtime/coroutine/TestMemLeak.java, test/runtime/coroutine/coroutineBreakpointSwitchToTest.c, test/runtime/coroutine/coroutineBreakpointSwitchToTest.sh, test/runtime/coroutine/logCompilationTest.sh
Summary: Bug fix for JKU coroutine
Test Plan: Coroutine tests
Reviewed-by: yuleil, shiyuexw, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/113
=> [Coroutine] Bug fixes for JKU coroutine

src/share/vm/runtime/arguments.cpp, src/share/vm/runtime/java.hpp
Summary: make EnableJFR obsolete
Test Plan: java -XX:+/-EnableJFR -version
Reviewed-by: zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/119
=> [Misc] Make EnableJFR obsolete

src/os_cpu/aix_ppc/vm/orderAccess_aix_ppc.inline.hpp, src/os_cpu/bsd_x86/vm/orderAccess_bsd_x86.inline.hpp, src/os_cpu/bsd_zero/vm/orderAccess_bsd_zero.inline.hpp, src/os_cpu/linux_ppc/vm/orderAccess_linux_ppc.inline.hpp, src/os_cpu/linux_sparc/vm/orderAccess_linux_sparc.inline.hpp, src/os_cpu/linux_x86/vm/orderAccess_linux_x86.inline.hpp, src/os_cpu/linux_zero/vm/orderAccess_linux_zero.inline.hpp, src/os_cpu/solaris_sparc/vm/orderAccess_solaris_sparc.inline.hpp, src/os_cpu/solaris_x86/vm/orderAccess_solaris_x86.inline.hpp, src/os_cpu/windows_x86/vm/orderAccess_windows_x86.inline.hpp, src/share/vm/jfr/recorder/checkpoint/types/traceid/jfrTraceIdEpoch.hpp, src/share/vm/runtime/orderAccess.hpp
Summary: fixed build failure on Windows
Test Plan: build successfully on Windows
Reviewed-by: zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/112
=> [JFR] Fixed build failure on Windows

test/elastic-heap/TestElasticHeapGenerationLimit.java
Summary: Fix G1ElasticHeap test case failure
Reviewed-by: Hao Tang, Yude Lin
Issue: https://github.com/alibaba/dragonwell8/issues/177
=> [Misc] Fix G1ElasticHeap test case failure

src/share/vm/runtime/coroutine.cpp, test/runtime/coroutine/JStackTest.java, test/runtime/coroutine/JStackWispControlGroupTest.java
Summary: Add more Wisp2 related information
Test Plan: all wisp tests
Reviewed-by: yuleil,zhengxiaolinX
Issue:https://github.com/alibaba/dragonwell8/issues/171
=> [Wisp] Add more information of jstack

src/share/vm/classfile/classLoaderData.hpp, src/share/vm/classfile/vmSymbols.hpp, src/share/vm/gc_interface/collectedHeap.cpp, src/share/vm/memory/binaryTreeDictionary.cpp, src/share/vm/memory/binaryTreeDictionary.hpp, src/share/vm/memory/metachunk.hpp, src/share/vm/memory/metaspace.cpp, src/share/vm/memory/metaspace.hpp, src/share/vm/memory/metaspaceDumper.cpp, src/share/vm/memory/metaspaceDumper.hpp, src/share/vm/oops/constantPool.hpp, src/share/vm/runtime/globals_ext.hpp, src/share/vm/runtime/java.cpp, src/share/vm/runtime/java.hpp, src/share/vm/runtime/thread.cpp, src/share/vm/runtime/timer.cpp, src/share/vm/runtime/timer.hpp, src/share/vm/runtime/vm_operations.hpp, src/share/vm/services/diagnosticCommand.cpp, src/share/vm/services/diagnosticCommand.hpp, src/share/vm/services/heapDumper.cpp, src/share/vm/utilities/dumpUtil.hpp, test/metaspace-dump/HeapDumpPathTest.java, test/metaspace-dump/MetaspaceDumpTest.java
Summary: ported metaspace dump to Dragonwell8
Test Plan: hotspot/test/metaspace-dump
Reviewed-by: joeyleeeeeee97, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/209
=> [RAS] Metaspace dump support

agent/src/share/classes/sun/jvm/hotspot/gc_interface/GCCause.java, src/share/vm/gc_implementation/g1/elasticHeap.cpp, src/share/vm/gc_implementation/g1/elasticHeap.hpp, src/share/vm/gc_implementation/g1/g1CollectedHeap.cpp, src/share/vm/gc_interface/gcCause.cpp, src/share/vm/gc_interface/gcCause.hpp, src/share/vm/services/diagnosticCommand.cpp, src/share/vm/services/diagnosticCommand.hpp, test/elastic-heap/TestElasticHeapPeriodicInitialMark.java, test/elastic-heap/TestElasticHeapSoftmxPercentFail.java, test/elastic-heap/TestElasticHeapSoftmxPercentFullGC.java
Summary: Enhance G1ElasticHeap to support softmx adjustment via jcmd full gc
Test Plan: hotspot/test/elastic-heap
Reviewed-by: Yude Lin, Hao Tang
Issue: https://github.com/alibaba/dragonwell8/issues/212
=> [GC] Enhance G1ElasticHeap to support softmx adjustment via jcmd full gc

src/share/vm/gc_implementation/g1/elasticHeap.cpp, src/share/vm/gc_implementation/g1/elasticHeap.hpp, src/share/vm/prims/whitebox.cpp, test/elastic-heap/TestElasticHeapGCLocker.java, test/testlibrary/whitebox/sun/hotspot/WhiteBox.java
Summary: G1ElasticHeap: Handle the failure of GC invoke from jcmd
Reviewed-by: Yude Lin, Hao Tang
Issue: https://github.com/alibaba/dragonwell8/issues/212
=> [GC] G1ElasticHeap: Handle the failure of GC invoke from jcmd

src/share/vm/prims/unsafe.cpp, src/share/vm/runtime/thread.cpp, src/share/vm/runtime/vm_operations.cpp, src/share/vm/runtime/vm_operations.hpp, src/share/vm/services/threadService.cpp, src/share/vm/services/threadService.hpp
This reverts commit 0219cd98da2f0a5676fd0baceebf1371aad12673.
=> Revert "[Wisp] Support threadMxbean in AllThreadAsWisp"

src/share/vm/runtime/coroutine.cpp, src/share/vm/runtime/coroutine.hpp
Summary: Continue to remove aarch64 code
Test Plan: existing x86 tests
Reviewed-by: zhengxiaolinX, joeyleeeeeee97
Issue: https://github.com/alibaba/dragonwell8/issues/228
=> [Misc] Remove remaining aarch64 code

src/share/vm/classfile/javaClasses.cpp, src/share/vm/classfile/javaClasses.hpp, src/share/vm/classfile/systemDictionary.hpp, src/share/vm/classfile/vmSymbols.hpp, src/share/vm/runtime/coroutine.cpp, test/runtime/coroutine/JStackWispContainerIdTest.java
Test Plan: jreg pipeline
Reviewed-by: yulei, joeyleeeeeee97, zhengxiaolinX
Issue: alibaba/dragonwell8#235
=> [Wisp] Jstack info for containerId added

src/share/vm/gc_implementation/g1/g1CollectedHeap.cpp, src/share/vm/runtime/synchronizer.cpp
Summary: Fix compile error in synchronizer.cpp
Reviewed-by: zhengxiaolinX, kelthuzadx
Issue: https://github.com/alibaba/dragonwell8/issues/248
=> [Misc] Fix compile error in synchronizer.cpp

test/runtime/coroutine/MemLeakTest.java, test/runtime/coroutine/TestAvoidDeoptCoroutineMethod.java
Summary: fix unstable coroutine tests
Test Plan: CI pipeline
Reviewed-by: zhengxiaolinX, yuleil
Issue: alibaba/dragonwell8#273
=> [Misc] fix unstable coroutine tests

src/share/vm/jwarmup/jitWarmUp.cpp
Summary:
JWarmup will crash if recorded classes name is empty. It happened
if class was transformed. JWarmup should skip these entries.
Test Plan: sanity test
Reviewed-by: sandlerwang, JoshuaZhuwj
Issue: https://aone.alibaba-inc.com/task/38064095
CR: https://github.com/alibaba/dragonwell8_hotspot/pull/101
=> [JIT] fix warmup compilation error by empty class name

src/share/vm/runtime/globals_ext.hpp, src/share/vm/runtime/sweeper.cpp, src/share/vm/runtime/sweeper.hpp, src/share/vm/runtime/thread.cpp
Summary:
Trigger code cache sweep periodly to recovert jit quickly
Test Plan: jittest case
Reviewed-by: JoshuaZhuwj, sandlerwang
Issue: https://github.com/alibaba/dragonwell8/issues/285
CR: https://github.com/alibaba/dragonwell8_hotspot/pull/106
=> [JIT] trigger code cache sweep periodly
