src/share/vm/trace/traceevents.xml

Summary:
remove useless fields of ThreadAllocationStatistics
Test Plan: jdk/test/jdk/jfr/event/runtime/TestThreadAllocationEvent.java
Reviewed-by: yfxhust, luchsh
Issue: #5

[JFR] Remove useless fields of ThreadAllocationStatistics

---

src/share/vm/opto/connode.cpp
test/compiler/c2/Test8217359.java

Summary: Add a use of the node `cx` to avoid it being destroyed.
Backport from [JDK-8217359](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8217359).
This patch of OpenJDK is available [here](https://hg.openjdk.java.net/jdk/jdk12/rev/44f41693631f).
Test Plan: test/compiler/c2/Test8217359.java
Reviewed-by: luchsh, kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/11

[C2] Backport JDK-8217359: C2 compiler triggers SIGSEGV after transformation in ConvI2LNode::Ideal

---

src/share/vm/services/heapDumper.hpp
test/serviceability/sa/jmap-minidump/TestNoMinidumpAtFullGC.java

Summary: _mini_dump is not initialized for all paths
Test Plan: test/serviceability/
Reviewed-by: D-D-H, kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/45

[RAS] Fixed uninitialized field of HeapDumper

---

src/share/vm/gc_interface/allocTracer.cpp
src/share/vm/gc_interface/allocTracer.hpp
src/share/vm/gc_interface/allocTracer.inline.hpp
src/share/vm/gc_interface/collectedHeap.hpp
src/share/vm/gc_interface/collectedHeap.inline.hpp
src/share/vm/opto/macro.cpp
src/share/vm/opto/macro.hpp
src/share/vm/opto/runtime.cpp
src/share/vm/opto/runtime.hpp

Summary: Fix build issues caused by object allocation profiling on Windows/Mac
Test Plan: build Dragonwell 8 successfully on Linux/Windows/Mac
Reviewed-by: zhengxiaolinX, luchsh, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/74

[JFR] Fix build issues caused by object allocation profiling on Windows/Mac

---

src/share/vm/gc_interface/allocTracer.cpp
src/share/vm/jfr/metadata/metadata.xml
src/share/vm/jfr/periodic/jfrPeriodic.cpp
src/share/vm/runtime/globals_ext.hpp
src/share/vm/runtime/safepoint.hpp
src/share/vm/utilities/globalDefinitions.hpp

Summary:
SafepointStatistics is a periodic event, both events are experimental
now and disbaled by default
Test Plan:
jdk/test/jdk/jfr/event/runtime/TestSafepointEvents.java
jdk/test/jdk/jfr/event/compiler/TestHugeObjectAllocationSample.java
jdk/test/jdk/jfr/event/metadata/TestLookForUntestedEvents.java
Reviewed-by: kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/116

[JFR] Added SafepointStatistics and HugeObjectAllocationSample Events

---

src/share/vm/jfr/metadata/metadata.xml
src/share/vm/jfr/support/jfrThreadLocal.cpp
src/share/vm/jfr/support/jfrThreadLocal.hpp
src/share/vm/prims/jni.cpp
src/share/vm/prims/jvm.cpp

Summary:
Test Plan: jdk/test/jdk/jfr/event/runtime/TestThreadStartEndEvents.java
Reviewed-by: zhengxiaolinX, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/127

[Backport] 8237499: JFR: Include stack trace in the ThreadStart event

---

src/share/vm/jfr/periodic/jfrPeriodic.cpp
src/share/vm/jfr/recorder/checkpoint/types/jfrType.cpp

Summary:
TRACE_REQUEST_FUNC(ThreadAllocationStatistics) in jfrPeriodic.cpp
void JfrCheckpointThreadClosure::do_thread(Thread* t) in jfrType.cpp
Test Plan: jdk/test/jdk/jfr
Reviewed-by: kelthuzadx, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/134

[JFR] Fixed missing Threads_lock protection when traversing thread list

---

src/share/vm/prims/unsafe.cpp
src/share/vm/runtime/thread.cpp
src/share/vm/runtime/vm_operations.cpp
src/share/vm/runtime/vm_operations.hpp
src/share/vm/services/threadService.cpp
src/share/vm/services/threadService.hpp

Summary: Now we can use ThreadMxBean to inspect coroutine infomation.
Test Plan: Support ThreadMxBean to inspect coroutine infomation,
including getThreadInfo, dumpAllThreads,getThreadCount, getAllThreadIds.
Reviewed-by: zhengxiaolinX, yuleil, sanhongli
Issue: https://github.com/alibaba/dragonwell8/issues/132

[Wisp] Support threadMxbean in AllThreadAsWisp

---

src/share/vm/gc_implementation/g1/g1RegionToSpaceMapper.hpp
src/share/vm/gc_implementation/g1/heapRegionManager.cpp

Summary: Elastic Heap should clear bitmap when committing region memory
Reviewed-by: Hao Tang, Yude Lin
https://github.com/alibaba/dragonwell8/issues/57

[GC] Elastic Heap should clear bitmap when committing region memory

---

src/share/vm/runtime/arguments.cpp

Summary: Wisp has platform-related code, which requires Wisp to be disabled in any other platform.
Test Plan: -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 on AArch64 platform, also other sanity tests
Reviewed-by: leiyul, ziyilin
Issue: alibaba/dragonwell8#157

[Wisp] Disable any platform but x86_64 for Wisp

---

src/cpu/aarch64/vm/aarch64.ad
src/cpu/aarch64/vm/c1_CodeStubs_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRGenerator_aarch64.cpp
src/cpu/aarch64/vm/c1_Runtime1_aarch64.cpp
src/cpu/aarch64/vm/coroutine_aarch64.cpp
src/cpu/aarch64/vm/coroutine_aarch64.hpp
src/cpu/aarch64/vm/interp_masm_aarch64.cpp
src/cpu/aarch64/vm/macroAssembler_aarch64.cpp
src/cpu/aarch64/vm/macroAssembler_aarch64.hpp
src/cpu/aarch64/vm/sharedRuntime_aarch64.cpp
src/cpu/aarch64/vm/stubGenerator_aarch64.cpp
src/cpu/aarch64/vm/templateInterpreter_aarch64.cpp
src/share/vm/c1/c1_Runtime1.cpp
src/share/vm/runtime/arguments.cpp
src/share/vm/runtime/coroutine.cpp
src/share/vm/runtime/coroutine.hpp

Summary: Support AArch64 platform for Wisp
1. Port JKU coroutine switch logic
2. Port monitor exit support for Wisp monitor
3. Port platform related coroutine work steal support
Test Plan: all wisp tests on AArch64 platform
Reviewed-by: leiyul, kuaiwei
Issue: alibaba/dragonwell8#173

[Wisp] Support AArch64 platform

---

src/cpu/aarch64/vm/c1_CodeStubs_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRGenerator_aarch64.cpp
src/cpu/aarch64/vm/sharedRuntime_aarch64.cpp
src/cpu/x86/vm/c1_CodeStubs_x86.cpp
src/cpu/x86/vm/c1_LIRAssembler_x86.cpp
src/cpu/x86/vm/c1_LIRGenerator_x86.cpp
src/cpu/x86/vm/sharedRuntime_x86_64.cpp
src/share/vm/c1/c1_CodeStubs.hpp
src/share/vm/c1/c1_GraphBuilder.cpp
src/share/vm/c1/c1_Instruction.hpp
src/share/vm/c1/c1_LIR.cpp
src/share/vm/c1/c1_LIR.hpp
src/share/vm/c1/c1_LIRGenerator.cpp
src/share/vm/c1/c1_LIRGenerator.hpp
src/share/vm/c1/c1_Runtime1.cpp
src/share/vm/opto/callnode.hpp
src/share/vm/opto/graphKit.cpp
src/share/vm/opto/graphKit.hpp
src/share/vm/opto/macro.cpp
src/share/vm/opto/parse1.cpp
src/share/vm/opto/runtime.cpp
src/share/vm/opto/runtime.hpp
src/share/vm/runtime/sharedRuntime.cpp
src/share/vm/runtime/sharedRuntime.hpp
test/runtime/coroutine/deopt/MultiThreadWispRunner.java
test/runtime/coroutine/deopt/TestMonitorExitDeopt.java
test/runtime/coroutine/deopt/TestSynchronizedMethodDeopt.java
test/runtime/coroutine/deopt/TestSynchronizedMethodDeoptInDoExits.java
test/runtime/coroutine/deopt/TestSynchronizedMethodWhenUnwindingDeopt.java

Summary: It has the possibility to get a deoptimization whenever entering into java code. 1. When this happens at calling Wisp.unpark at the bytecode _return of synchronized methods, it is going to crash or error because the origin deopt logic cannot handle the _return bytecode; 2. For synchronized blocks, the unlocked monitor shouldn't be recorded into the debuginfo so that an illegalMonitorStateException will be thrown out.
Test Plan: `test/jdk/com/alibaba/wisp/monitor/deopt/*`, which can reproduce this issue.
Reviewed-by: leiyul, kuaiwei
Issue: alibaba/dragonwell8#172

[Wisp] Fix deoptimization when monitorexit calls java in synchronized methods or blocks

---

src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp

Summary: add return statement after ShouldNotReachHere();
Test Plan: AdoptJDK CI pipeline
Reviewed-by: joeyleeeeeee97, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/199

[Misc] Fix compilation error on aarch64

---

src/share/vm/classfile/javaClasses.cpp
src/share/vm/classfile/javaClasses.hpp
src/share/vm/classfile/systemDictionary.hpp
src/share/vm/classfile/vmSymbols.hpp
src/share/vm/runtime/coroutine.cpp
test/runtime/coroutine/JStackWispControlGroupTest.java

Summary: Add more three fields in output of jstack, they are ttr/cfsPeriod/cfsQuota,
which could help to debug wisp control group issues.
Test Plan: add ut JStackWispControlGroupTest.
Reviewers: lei.yul, sanhong.lsh, joeylee.lz
Issue: https://github.com/alibaba/dragonwell8/issues/183

[Wisp] Enhance output of jstack for WispControlGroup related statistics

---

src/share/vm/memory/allocation.hpp
src/share/vm/runtime/coroutine.cpp
src/share/vm/runtime/coroutine.hpp
src/share/vm/services/memReporter.cpp
src/share/vm/services/nmtCommon.cpp
test/runtime/coroutine/NmtTracingWispStackTest.java

Summary:
refactor wisp task's jvm native memory utilization classification
and add a new native memory label for NMT.
Test Plan:
hotspot/test/runtime/coroutine/NmtTracingWispStackTest.java
Reviewed-by: lei.yul, sanhong.lsh, joeylee.lz
Issue: alibaba/dragonwell8#191

[Wisp] make wisp task's stack space size traceable by NMT

---

src/share/vm/runtime/coroutine.cpp

[Wisp] Use MutexLockerEx for Wisp_lock: unpark should not yield any safepoint because of deoptimization problem
Summary: We need to use MutexLockerEx, as well as the lock rank 'special' because unpark couldn't yield any safepoint due to deoptimization problem
Test Plan: all wisp tests
Reviewed-by: leiyul, joeyleeeeeee97
Issue: alibaba/dragonwell8#182

[Wisp] Use MutexLockerEx for Wisp_lock: unpark should not yield any safepoint because of deoptimization problem

---

src/share/vm/interpreter/interpreterRuntime.cpp
src/share/vm/prims/unsafe.cpp
src/share/vm/runtime/coroutine.cpp
src/share/vm/runtime/coroutine.hpp
src/share/vm/runtime/safepoint.cpp
src/share/vm/runtime/safepoint.hpp

Summary: Preempt check could be left out when thread fall into
interpreter or unhandled thread_state, this patch added check
in interpreter and cleared preempted flag when needed.
Test Plan: com/alibaba/wisp/thread/PreemptTest.java
Reviewed-by: leiyu, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/204

[Wisp] Support preempt in interpreter

---

src/share/vm/memory/metaspaceDumper.cpp
src/share/vm/runtime/thread.cpp

Summary: use portable __VA_ARGS__ in macro
Test Plan: build
Reviewed-by: joeyleeeeeee97, yuleil
Issue: alibaba/dragonwell8#210

[RAS] Fix compilation error caused by Metaspace dump on Windows

---

src/share/vm/gc_implementation/g1/elasticHeap.cpp
src/share/vm/runtime/globals_ext.hpp
test/elastic-heap/TestElasticHeapMisc.java

Summary: Elastic related info is printed only when -XX:+PrintGCDetails is set.
Test Plan: hotspot/test/elastic-heap
Reviewed by: maoliang.ml, yude.lyd
Issue: https://github.com/alibaba/dragonwell8/issues/201

[GC] Print elastic heap log under -XX:+PrintGCDetails

---

src/share/vm/c1/c1_LIRGenerator.cpp
test/runtime/coroutine/deopt/TestSynchronizedMethodC1Crash.java

Summary: MonitorExit introduces new 'State' to generate OopMaps and Debuginfo, yet dead locals on the 'State' doesn't get cleaned. We need to clean them because all locals are dead after the implicit monitorexit.
Test Plan: deopt/TestSynchronizedMethodC1Crash.java, which can reproduce this issue.
Reviewed-by: leiyul, sandlerwang, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/216

[Wisp] C1: Clear dead locals for MonitorExit that copies state to generate debuginfo

---

src/share/vm/jfr/recorder/checkpoint/types/jfrType.cpp
src/share/vm/runtime/mutex.cpp
src/share/vm/runtime/thread.hpp

Summary: allow to skip the check of rank order
Test Plan: jdk/test/jdk/jfr
Reviewed-by: kelthuzadx, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/223

[JFR] Crash in Monitor::set_owner_implementation on slow debug build

---

src/cpu/aarch64/vm/aarch64.ad
src/cpu/aarch64/vm/c1_CodeStubs_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRAssembler_aarch64.cpp
src/cpu/aarch64/vm/c1_LIRGenerator_aarch64.cpp
src/cpu/aarch64/vm/c1_Runtime1_aarch64.cpp
src/cpu/aarch64/vm/coroutine_aarch64.cpp
src/cpu/aarch64/vm/coroutine_aarch64.hpp
src/cpu/aarch64/vm/interp_masm_aarch64.cpp
src/cpu/aarch64/vm/macroAssembler_aarch64.cpp
src/cpu/aarch64/vm/macroAssembler_aarch64.hpp
src/cpu/aarch64/vm/sharedRuntime_aarch64.cpp
src/cpu/aarch64/vm/stubGenerator_aarch64.cpp
src/cpu/aarch64/vm/templateInterpreter_aarch64.cpp
src/share/vm/runtime/coroutine.cpp
src/share/vm/runtime/coroutine.hpp

Summary: Support AArch64 platform for Wisp based on the latest AArch64 port
Test Plan: all wisp tests on AArch64 platform
Reviewed-by: leiyul, sandlerwang
Issue: alibaba/dragonwell8#233

[Wisp] Support AArch64 platform based on the latest AArch64 port

---

src/share/vm/jfr/jni/jfrJniMethod.cpp
src/share/vm/jfr/leakprofiler/sampling/objectSampler.cpp
src/share/vm/jfr/recorder/jfrEventSetting.cpp
src/share/vm/jfr/recorder/jfrEventSetting.hpp
src/share/vm/jfr/recorder/service/jfrEvent.hpp
src/share/vm/jfr/recorder/stacktrace/jfrStackTrace.cpp
src/share/vm/jfr/recorder/stacktrace/jfrStackTrace.hpp
src/share/vm/jfr/recorder/stacktrace/jfrStackTraceRepository.cpp
src/share/vm/jfr/recorder/stacktrace/jfrStackTraceRepository.hpp
src/share/vm/jfr/support/jfrFlush.cpp
src/share/vm/jfr/support/jfrFlush.hpp
src/share/vm/jfr/support/jfrStackTraceMark.cpp
src/share/vm/jfr/support/jfrThreadLocal.cpp
src/share/vm/jfr/support/jfrThreadLocal.hpp
src/share/vm/opto/macro.cpp
src/share/vm/opto/macro.hpp
src/share/vm/opto/runtime.cpp
src/share/vm/opto/runtime.hpp
src/share/vm/prims/jvm.cpp

Summary:
1. Use CallStaticJavaNode to invoke jfr_fast_object_alloc_C so that
last_java_sp is set properly
2. Remove StackWalkMode and _cached_top_frame_bci
Test Plan:
test/jdk/jfr/event/objectsprofiling/TestOptoObjectAllocationsSampling.java
Reviewed-by: kelthuzadx, kuaiwei, sandlerwang, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell11/issues/189

[JFR] Fix object profiling stacktrace problem on aarch64 platform

---

src/share/vm/code/nmethod.cpp
src/share/vm/code/nmethod.hpp
src/share/vm/oops/instanceKlass.cpp
src/share/vm/oops/instanceKlass.hpp
src/share/vm/runtime/sweeper.cpp
src/share/vm/runtime/sweeper.hpp

Summary:
8023191 : OSR nmethods should be flushed to free space in CodeCache
8152947 : VM crash with assert(!removed || is_in_use()) failed: unused
osr nmethod should be invalidated
origin bug: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8023191
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8152947
review url: http://cr.openjdk.java.net/~thartmann/8023191/webrev.01/
http://cr.openjdk.java.net/~thartmann/8152947/webrev.01/
Reviewers: JoshuaZhuwj, sandlerwang
Issue: https://github.com/alibaba/dragonwell8/issues/284
CR: https://github.com/alibaba/dragonwell8_hotspot/pull/104

[JIT] backport: flush OSR nmethods in code cache

---

src/share/vm/jfr/recorder/checkpoint/types/jfrTypeSet.cpp

Summary: remove the wrong parameter
Test Plan: jtreg jdk/jfr
Reviewed-by: kelthuzadx, joeyleeeeeee97, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/296

[JFR] A wrong parameter is passed to the constructor of LeakKlassWriter
